/* UI adapters for the eight new games. Shared pause, score, audio and input. */
(function(root){
'use strict';
const A=root.PigArcadeCore;
const configs={
 blocks:{name:'猪猪方块',icon:'i-blocks',title:'一排小猪，整整齐齐。',subtitle:'落下的小方块也想排好队。填满一行，就能腾出新的空间。',tag:'落块消行 · 预览 / 暂存 / 落点影子',eyebrow:'07 / LITTLE BLOCKS',note:'一次消掉四行，会有小猪来庆祝。',levels:[],labels:['本局得分','已消行数','最高得分'],tips:[['先想位置，再落下','← → / A D 移动，↑ / W 旋转，Z 反向旋转，↓ / S 加速，空格直接落底。'],['留一条直通的路','右侧显示下一块；虚线影子显示落点。C / Shift 暂存，每块只能暂存一次。'],['一次消多行','每 10 行加快一级。接触地面后有短暂调整时间，堆到出生位置就结束。']]},
 breakout:{name:'弹弹猪',icon:'i-breakout',title:'接住小球，撞开彩虹。',subtitle:'弹一弹，小猪的彩色积木就散开了。角度由你决定。',tag:'打砖块 · 三条生命 / 三座牧场',eyebrow:'08 / LITTLE BOUNCES',note:'接板边缘会弹得更斜，绿色礼物能加宽接板。',levels:[['easy','轻松接球'],['hard','挑战手感']],labels:['本局得分','剩余生命','最高得分'],tips:[['接板跟着你走','鼠标移动、手指拖动，或 ← → / A D 移动接板。点击 / 空格发球。'],['边缘改变角度','球落在接板中间会向上，落在两侧会斜着飞。漏球扣一条生命。'],['三座牧场','清完积木进入下一关；有些积木要撞两次。接到绿色礼物可加宽 12 秒。']]},
 flappy:{name:'飞天猪',icon:'i-wing',title:'小短腿，也有飞行梦。',subtitle:'轻轻拍一下，带小猪穿过薄荷色的拱门。稳住，就是胜利。',tag:'一键飞行 · 越飞越远',eyebrow:'09 / LITTLE WINGS',note:'轻点，轻点，再轻点。',levels:[['easy','宽宽的门'],['hard','小小的门']],labels:['穿过拱门','飞行米数','最高纪录'],tips:[['轻点一下就扑翅','空格 / ↑ / W、点击画面或“扑翅”按钮；每次按下只扑一次。'],['瞄准门的中间','持续受到重力，按得太快会飞高，太慢会落地。'],['别碰边缘','碰到拱门、天花板或地面就结束；每穿过一扇门得 1 分。']]},
 stack:{name:'叠叠猪',icon:'i-stack',title:'把小猪的房子，叠到云上。',subtitle:'看准上一层，轻轻落下。对得越齐，房子越高。',tag:'一键叠高 · 完美落点奖励',eyebrow:'10 / LITTLE TOWER',note:'没对齐的部分会掉落，完美落下能保住宽度。',levels:[],labels:['楼层高度','完美落点','最高楼层'],tips:[['看准再落','空格 / ↓ / S、点击画面或“放下这一层”。方块会左右移动。'],['重叠的部分留下','没有重叠便结束；偏出去的部分会被切掉，下一层越来越窄。'],['完美对齐','偏差很小时自动对齐，保留全部宽度。越往上，移动越快。']]},
 connect:{name:'猪猪四子棋',icon:'i-connect',title:'四只小猪，手拉手。',subtitle:'让四枚同色棋子连成一线，和猪猪对手斗斗智，也可以两个人一起玩。',tag:'策略对战 · 单人 / 双人同屏',eyebrow:'11 / LITTLE STRATEGY',note:'横、竖、斜着连成四个都算。',levels:[['easy','悠闲对手'],['hard','聪明对手'],['duo','双人同屏']],labels:['当前回合','落子步数','累计胜场'],tips:[['点一列，棋子落下','点列顶按钮或棋盘格，棋子会落到该列最低的空位。也可按数字 1–7。'],['先连成四个','横、竖、两种斜线均可，满盘未分胜负就是平局。粉色先手。'],['留意两头都有路','先挡住对手的三连，再争取同时制造两处威胁。聪明对手会提前思考。']]},
 sokoban:{name:'松露推箱子',icon:'i-box',title:'把每份礼物，送到家。',subtitle:'小猪只能推、不能拉。多绕一步，可能就找到新办法。',tag:'12 个关卡 · 无限撤销 / 一步提示',eyebrow:'12 / LITTLE DELIVERY',note:'箱子进了墙角可能推不回来，撤销随时救场。',levels:A.SOKO_LEVELS.map((x,i)=>['l'+(i+1),'第 '+(i+1)+' 关 · '+x[0]]),labels:['行走步数','已入库箱子','最佳步数'],tips:[['推到花朵位置','方向键 / WASD 或下方按钮移动；把全部箱子推上花朵就过关。'],['只能向前推','不能拉箱子，也不能一次推动两个。把箱子推到非目标墙角会卡住。'],['撤销与提示','Z / 按钮无限撤销。提示只告诉你下一步方向；完成一关后可进入下一关。']]},
 lights:{name:'猪猪点灯',icon:'i-light',title:'晚安，把星星灯关好。',subtitle:'轻点一盏灯，它和上下左右的邻居一起翻转。找出让它们全暗的办法。',tag:'逻辑谜题 · 每一局都有解',eyebrow:'13 / LITTLE STARS',note:'点两次等于没点；操作顺序不影响结果。',levels:[['easy','3×3 星光'],['normal','4×4 月光'],['hard','5×5 夜空']],labels:['点击次数','仍亮灯数','最佳步数'],tips:[['点一下，翻五盏','翻转当前灯及上下左右邻灯；边角位置的邻灯少一些。目标是全部关掉。'],['每局保证能解','初始局面来自合法翻转；提示会圈出可行下一步，Z 可以撤销。'],['从上一行找线索','观察上一行亮灯，试着按它下方的灯，逐行把光推到底部。']]},
 match:{name:'猪猪消消乐',icon:'i-match',title:'好朋友，也有厉害的小特技。',subtitle:'四连变火箭，五连变彩虹。让六种彩色小猪一起破冰，接出更漂亮的连锁。',tag:'特技三消 · 交换 / 连锁 / 破冰 / 收集',eyebrow:'14 / LITTLE COMBOS',note:'四连、五连和 T / L 形会留下特殊猪；特殊猪互换还能组合。',levels:[['easy','特技入门 · 28 步'],['normal','破冰收集 · 28 步'],['hard','双层冰挑战 · 30 步']],labels:['本局得分','剩余步数','最高得分'],tips:[['六种颜色，六种服饰','点击相邻两只，或拖动一格交换。相同颜色与造型的三只成行即可消除；无效交换会滑回去，不扣步数。'],['创造与组合特殊猪','四连生成横 / 竖火箭猪，T / L 形生成 3×3 爆爆猪，五连生成同色全清彩虹猪。特殊猪与邻居交换发动，两只特殊猪互换有组合技。'],['先看目标，再想交换','入门只需得分；后两档还要破完冰层、收集指定小猪。每次消除可打掉一层冰；无路重排会保留特殊猪和目标。']]}
};
function create(ui){
 const {$,Sound,Store,icon,message,stats,record,result,confetti}=ui;
 const get=()=>ui.get(),s=()=>get().state;
 let keys=new Set(),sprites=[];
 const img=role=>`<img src="${ui.pigSrc(role)}" data-pig-role="${role||'pig'}" data-pig-sprite alt="" draggable="false">`;
 const has=id=>Object.prototype.hasOwnProperty.call(configs,id);
 function status(){const {game,state:t}=get(),g=t.g;
  if(game==='blocks')stats(g.score,g.lines);if(game==='breakout')stats(g.score,g.lives);if(game==='flappy')stats(g.score,Math.floor(g.distance/20));if(game==='stack')stats(g.score,g.perfect);
  if(game==='connect')stats(g.over?(g.winner?'胜负已分':'平局'):g.turn===1?'粉色小猪':get().level==='duo'?'薄荷小猪':'猪猪思考中',g.moves);
  if(game==='sokoban')stats(g.moves,[...g.boxes].filter(i=>g.goals.has(i)).length+' / '+g.goals.size);if(game==='lights')stats(g.moves,g.board.filter(Boolean).length);
  if(game==='match')stats((t.matchView||g).score,(t.matchView||g).moves)
 }
 function end(title,body,win,value,lower){const t=s();if(t.finished)return;t.finished=true;keys.clear();if(value!==undefined)record(value,lower);status();if(win){Sound.win();confetti(36)}else Sound.lose();result(title,body,win)}
 function start(){const t=s();if(t.finished||get().paused)return false;if(!t.started){t.started=true;ui.setRunning(true);const layer=$('extra-start');if(layer)layer.hidden=true;Sound.greet();message('出发！祝你玩得开心。')}return true}
 function makeCanvas(W,H,label,pad){const t=s();t.W=W;t.H=H;$('board').innerHTML=`<div class="canvas-wrap extra-canvas"><canvas id="extra-canvas" tabindex="0" aria-label="${label}"></canvas><div class="start-overlay" id="extra-start"><button class="primary" id="extra-go">${icon('i-play','sm')}开始游玩</button><small>也可以直接按操作键开始</small></div></div><div class="arcade-pad">${pad}</div>`;
  t.cv=$('extra-canvas');t.ctx=t.cv.getContext('2d');$('extra-go').onclick=()=>action('start');t.cv.onpointerdown=e=>{if(e.button>0||get().paused)return;e.preventDefault();if(get().game==='breakout'){aimPointer(e);action('launch')}else if(get().game==='flappy')action('flap');else if(get().game==='stack')action('drop');else t.cv.focus({preventScroll:true})};
  if(get().game==='breakout'){t.cv.onpointermove=e=>{if(!get().paused)aimPointer(e)};t.cv.onpointerdown=e=>{if(e.button>0||get().paused)return;e.preventDefault();try{t.cv.setPointerCapture(e.pointerId)}catch(err){}aimPointer(e);action('launch')}}
  document.querySelectorAll('[data-extra]').forEach(b=>{const a=b.dataset.extra;if(a==='left'||a==='right'){b.onpointerdown=e=>{e.preventDefault();if(!start())return;keys.add(a);if(get().game==='blocks')action(a);try{b.setPointerCapture(e.pointerId)}catch(err){}};b.onpointerup=b.onpointercancel=()=>keys.delete(a);b.onclick=e=>{if(e.detail===0)action(a)}}else b.onclick=()=>action(a)});resize();draw()
 }
 const button=(a,text,cls)=>`<button class="${cls||'secondary'}" data-extra="${a}" aria-label="${text}">${text}</button>`;
 const Match=root.PigMatchUI.create(ui,{button,bindToolbar,end});
 function aimPointer(e){const t=s(),r=t.cv.getBoundingClientRect();t.g.aim((e.clientX-r.left)*t.W/r.width)}
 function init(id){keys.clear();const t={started:false,finished:false,repeat:0};ui.setState(t);const l=get().level;
  if(id==='blocks'){t.g=new A.Blocks();makeCanvas(440,440,'猪猪方块棋盘',button('left','左移')+button('rotate','旋转')+button('right','右移')+button('soft','下移')+button('hold','暂存')+button('drop','直接落下','primary'));message('空格落底，↑ 旋转，C 暂存。填满一行即可消除。')}
  if(id==='breakout'){t.g=new A.Breakout(l==='hard');makeCanvas(760,420,'弹弹猪画面',button('left','向左')+button('launch','发球','primary')+button('right','向右'));message('移动接板，点击或空格发球。绿色礼物能让接板变宽。')}
  if(id==='flappy'){t.g=new A.Flappy(l==='easy');makeCanvas(760,420,'飞天猪画面',button('flap','扑翅','primary'));message('空格、↑、点击画面都能扑翅。别碰拱门和地面。')}
  if(id==='stack'){t.g=new A.Stack();makeCanvas(600,460,'叠叠猪画面',button('drop','放下这一层','primary'));message('看准重叠的位置，空格或点击让这一层落下。')}
  if(id==='connect'){t.g=new A.Connect();t.started=true;t.aiAt=0;ui.setRunning(true);renderConnect();message(l==='duo'?'粉色先手，两人轮流点列顶或棋盘。':'你是粉色小猪，先手。点一列，让棋子落下。')}
  if(id==='sokoban'){t.g=new A.Sokoban(parseInt(l.slice(1),10)-1);t.started=true;ui.setRunning(true);$('play-toolbar').innerHTML=button('undo','撤销（Z）')+button('hint','一步提示')+'<span class="key-hint">方向键 / WASD · 箱子只能推</span>';bindToolbar();$('board').innerHTML='<div id="soko-grid" class="soko-grid" role="group" aria-label="推箱子棋盘"></div>'+ui.dpadHTML();document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>action(b.dataset.dir));renderSoko();message('第 '+(t.g.index+1)+' 关：'+t.g.name+'。把每个箱子推到花朵上。')}
  if(id==='lights'){t.g=new A.Lights({easy:3,normal:4,hard:5}[l]);t.started=true;ui.setRunning(true);$('play-toolbar').innerHTML=button('undo','撤销（Z）')+button('hint','圈出下一步');bindToolbar();$('board').innerHTML='<div id="lights-grid" class="lights-grid" role="group" aria-label="点灯棋盘"></div>';renderLights();message('把灯全部关掉。每次会同时翻转上下左右的邻灯。')}
  if(id==='match')Match.init();
  status()
 }
 function bindToolbar(){document.querySelectorAll('#play-toolbar [data-extra]').forEach(b=>b.onclick=()=>action(b.dataset.extra))}
 function action(a){const {game:id,paused}=get(),t=s();if(paused||t.finished)return;const g=t.g;
  if(['blocks','breakout','flappy','stack'].includes(id)&&!start())return;
  if(id==='blocks'){let event=null;if(a==='left'||a==='right'){if(g.move(a==='left'?-1:1))Sound.turnTick()}if(a==='rotate'||a==='reverse'){if(g.rotate(a==='reverse'))Sound.blockRotate()}if(a==='hold'){if(g.swapHold())Sound.undo()}if(a==='soft')g.down(true);if(a==='drop')event=g.drop();blocksEvent(event);status();draw()}
  if(id==='breakout'){if(a==='launch'||a==='start'){if(g.launch())Sound.paddleBounce()}else if(a==='left'||a==='right')g.aim(g.paddle.x+(a==='left'?-35:35))}
  if(id==='flappy'){if(g.flap())Sound.flapWing()}
  if(id==='stack'&&a==='drop'){const ev=g.drop();if(ev.type==='miss'){Sound.pigWhimper();}if(ev.type==='miss')end('房子晃了一下。','你盖到了 '+g.score+' 层，完美落点 '+g.perfect+' 次。再来盖得更高吧！',false,g.score);else{Sound.stackLand(ev.type==='perfect');message(ev.type==='perfect'?'完美对齐！全部宽度都留下啦。':'可用宽度还剩 '+Math.max(1,Math.round(ev.width/g.layers[0].w*100))+'%。稳住下一层。')}status();draw()}
  if(id==='sokoban'){if(a==='undo'){if(g.undo()){Sound.undo();renderSoko();status();message('已撤销，可以换个方向试试。')}}else if(a==='hint'){const path=A.solveSokoban(g);message(path&&path.length?'试着向'+dirName(path[0])+'走一步。':path?'箱子都已经到家了。':'当前箱子可能卡住了，试试撤销或重新开始。');Sound.hintSpark()}else if(directions[a]){const moved=g.move(a);if(!moved){Sound.tone(180,{dur:.05,gain:.03});message('那边是墙，或者箱子后面被挡住了，推不动。','warn')}if(moved){if(moved.pushing)Sound.boxPush(g.goals.has(g.player+directions[a][0]+directions[a][1]*g.w));else Sound.turnTick();renderSoko();status();if(g.won){end('礼物都送到家啦！','第 '+(g.index+1)+' 关用了 '+g.moves+' 步，推动 '+g.pushes+' 次。',true,g.moves,true);if(g.index+1<A.SOKO_LEVELS.length){const b=document.createElement('button');b.className='primary';b.textContent='下一关';b.onclick=()=>ui.nextLevel('l'+(g.index+2));document.querySelector('#result .result-actions').appendChild(b)}}}}}
  if(id==='lights'){if(a==='undo'){if(g.undo()){t.hint=-1;Sound.undo();renderLights();status()}}if(a==='hint'){t.hint=g.hint();renderLights();Sound.hintSpark();message('圈出的灯可以作为下一步。点完还可以继续要提示。')}}
  if(id==='match'&&a==='hint'&&!t.pending)Match.hint();
 }
 const directions={left:[-1,0],right:[1,0],up:[0,-1],down:[0,1]},dirName=d=>({left:'左',right:'右',up:'上',down:'下'})[d];
 function blocksEvent(ev){if(ev){if(ev.lines){Sound.blockClear(ev.lines);message(ev.lines===4?'四行一起消除，太漂亮啦！':'消掉 '+ev.lines+' 行'+(s().g.combo>0?'，连续消行 ×'+(s().g.combo+1):'')+'。')}else Sound.blockLand()}if(s().g.over)end('小猪方块住满啦。','本局 '+s().g.score+' 分，消掉 '+s().g.lines+' 行。',false,s().g.score)}
 function dropConnect(col){const {level:l,paused}=get(),t=s(),g=t.g;if(paused||t.finished||(l!=='duo'&&g.turn===2))return;const ev=g.drop(col);if(!ev){message('这一列已经满啦，换一列吧。','warn');return}Sound.chessDrop(ev.p);renderConnect();status();connectEnd();if(!g.over&&l!=='duo')t.aiAt=get().elapsed+420}
 function connectEnd(){const {level:l}=get(),g=s().g;if(!g.over)return;if(!g.winner){end('握握小蹄子，平局！','棋盘住满了，两边都没有四连。',true);return}const win=l==='duo'||g.winner===1;if(win){const wins=Store.get('connect-'+l,0)+1;record(wins)}end(l==='duo'?(g.winner===1?'粉色小猪':'薄荷小猪')+'获胜！':win?'四只小猪，连起来啦！':'猪猪对手抢先一步。','用了 '+g.moves+' 步，'+(l==='duo'?'再换个先手试试吧。':win?'漂亮的一条线！':'留意对方两头都能接的三连。'),win)}
 function renderConnect(){const g=s().g;let html='<div class="connect-columns">';for(let c=0;c<7;c++)html+=`<button data-col="${c}" aria-label="第 ${c+1} 列落子" ${g.row(c)<0||g.over?'disabled':''}>${icon('i-arrow')}<small>${c+1}</small></button>`;html+='</div><div class="connect-grid">';for(let i=0;i<42;i++)html+=`<button data-col="${i%7}" class="connect-cell p${g.board[i]} ${g.line.includes(i)?'winning':''}" aria-label="第 ${Math.floor(i/7)+1} 行第 ${i%7+1} 列，${g.board[i]===1?'粉色':g.board[i]===2?'薄荷':'空位'}">${g.board[i]?img(g.board[i]===1?'pig':'flower'):''}</button>`;html+='</div>';$('board').innerHTML='<div class="connect-wrap">'+html+'</div>';document.querySelectorAll('[data-col]').forEach(b=>b.onclick=()=>dropConnect(+b.dataset.col))}
 function renderSoko(){const g=s().g,box=$('soko-grid');box.style.setProperty('--cols',g.w);let html='';for(let i=0;i<g.w*g.h;i++){const wall=g.walls.has(i),goal=g.goals.has(i),crate=g.boxes.has(i);html+=`<div class="soko-cell ${wall?'wall':''} ${goal?'goal':''} ${crate?'crate':''} ${goal&&crate?'stored':''}" role="img" aria-label="${Math.floor(i/g.w)+1} 行 ${i%g.w+1} 列，${wall?'墙':i===g.player?'小猪':crate?'箱子'+(goal?'已入库':''):goal?'目标':'空地'}">${wall?'':i===g.player?img('pig'):crate?icon('i-box'):goal?icon('i-flower'):''}</div>`}box.innerHTML=html;const undo=$('play-toolbar').querySelector('[data-extra="undo"]');undo.disabled=!g.history.length}
 function renderLights(){const t=s(),g=t.g,box=$('lights-grid');box.style.setProperty('--cols',g.n);box.innerHTML=g.board.map((v,i)=>`<button class="light-cell ${v?'lit':''} ${i===t.hint?'hinted':''}" data-light="${i}" aria-label="${Math.floor(i/g.n)+1} 行 ${i%g.n+1} 列，灯${v?'亮':'灭'}" aria-pressed="${!!v}">${icon('i-light')}<span>${v?'亮':'灭'}</span></button>`).join('');box.querySelectorAll('[data-light]').forEach(b=>b.onclick=()=>{if(get().paused||t.finished)return;const i=+b.dataset.light,on=g.board[i];if(g.press(i)){t.hint=-1;Sound.lightFlip(!on);renderLights();status();if(g.won)end('晚安，星星灯。','你用 '+g.moves+' 次点击关好了所有灯。小猪可以安心睡啦。',true,g.moves,true)}});$('play-toolbar').querySelector('[data-extra="undo"]').disabled=!g.history.length}
 function tick(dt){const {game:id,paused,elapsed}=get(),t=s();if(!has(id)||!t)return;const g=t.g;
  if(paused||t.finished||!t.started){draw();return}
  if(id==='blocks'){t.repeat+=dt;if((keys.has('left')||keys.has('right'))&&t.repeat>=100){t.repeat=0;g.move(keys.has('left')?-1:1)}if(keys.has('soft')){t.soft=(t.soft||0)+dt;if(t.soft>=40){g.down(true);t.soft=0}}blocksEvent(g.update(dt/1000));status()}
  if(id==='breakout'){const events=g.update(dt/1000,(keys.has('right')?1:0)-(keys.has('left')?1:0));if(events.includes('brick'))Sound.brickPop();else if(events.includes('bounce'))Sound.paddleBounce();if(events.includes('wide')){Sound.gold();message('接板加宽啦，持续 12 秒。')}if(events.includes('life')){Sound.miss();Sound.pigYelp({delay:.12});message(g.lives?'漏了一球，还有 '+g.lives+' 条生命。点击或空格重新发球。':'三条生命用完啦。')}if(events.includes('round')){Sound.milestone();message('第 '+g.round+' 座牧场！点击或空格发球。')}if(g.over)end(g.won?'彩虹牧场，全部打开！':'小球去散步啦。','本局 '+g.score+' 分，打到第 '+g.round+' 座牧场。',g.won,g.score);status()}
  if(id==='flappy'){const events=g.update(dt/1000);if(events.includes('point')){Sound.gatePass(g.score);message('穿过 '+g.score+' 扇拱门，稳住！')}if(g.over)end('小猪降落啦。','穿过 '+g.score+' 扇拱门，飞了 '+Math.floor(g.distance/20)+' 米。',false,g.score);status()}
  if(id==='stack')g.update(dt/1000);
  if(id==='connect'&&t.aiAt&&elapsed>=t.aiAt&&!g.over){t.aiAt=0;const col=A.chooseConnect(g.board,2,get().level==='hard'?4:1);g.drop(col);Sound.chessDrop(2);renderConnect();status();connectEnd()}
  if(id==='match')Match.tick();
  draw()
 }
 function resize(){const t=s();if(!t||!t.cv)return;const r=t.cv.parentElement.getBoundingClientRect(),availH=Math.max(250,window.innerHeight-r.top-105),scale=Math.min((r.width||600)/t.W,availH/t.H,1.25),w=Math.max(1,Math.floor(t.W*scale)),h=Math.max(1,Math.floor(t.H*scale)),dpr=Math.min(2,window.devicePixelRatio||1);t.cv.width=Math.round(w*dpr);t.cv.height=Math.round(h*dpr);t.cv.style.width=w+'px';t.cv.style.height=h+'px';t.ctx.setTransform(w/t.W*dpr,0,0,h/t.H*dpr,0,0);draw()}
 const palette=['#f0acba','#efcf86','#a6c9a3','#92bfca','#bfaddd','#ecb190','#8ca89d'];
 function roundRect(c,x,y,w,h,r,fill){if(w<=0||h<=0)return;ui.rr(c,x,y,w,h,Math.min(r,w/2,h/2));c.fillStyle=fill;c.fill()}
 function text(c,label,x,y,size,color,align){c.fillStyle=color||'#596a56';c.font='600 '+(size||14)+'px "Microsoft YaHei", sans-serif';c.textAlign=align||'left';c.fillText(label,x,y);c.textAlign='left'}
 function pig(c,x,y,size,role){let im=sprites[role||'pig'];if(!im){im=new Image();im.src=ui.pigSrc(role);sprites[role||'pig']=im}if(im.complete&&im.naturalWidth)c.drawImage(im,x-size/2,y-size/2,size,size)}
 function sky(c,W,H,night){c.fillStyle=night?'#e9e8f4':'#e9f2e8';c.fillRect(0,0,W,H);c.fillStyle='rgba(255,255,255,.8)';for(let k=0;k<4;k++){const x=70+k*220,y=35+k%2*36;roundRect(c,x,y,98,23,12,'rgba(255,255,255,.8)');roundRect(c,x+20,y-12,49,31,16,'rgba(255,255,255,.8)')}}
 function draw(){const {game:id}=get(),t=s();if(!has(id)||!t||!t.ctx)return;const c=t.ctx,g=t.g;c.clearRect(0,0,t.W,t.H);
  if(id==='blocks'){roundRect(c,0,0,440,440,14,'#eef0e4');roundRect(c,16,12,210,416,12,'#3b4e43');const cell=20,x=21,y=20;for(let r=0;r<20;r++)for(let col=0;col<10;col++){const v=g.board[r][col];if(v)block(c,x+col*cell,y+r*cell,cell,v);else{c.fillStyle='rgba(255,255,255,.05)';c.fillRect(x+col*cell+1,y+r*cell+1,18,18)}}
   const p=g.piece;if(!g.over){const gy=g.ghostY();for(let r=0;r<p.m.length;r++)for(let col=0;col<p.m[r].length;col++)if(p.m[r][col]){c.strokeStyle='#d5dfc1';c.lineWidth=1;c.strokeRect(x+(p.x+col)*cell+3,y+(gy+r)*cell+3,14,14)}for(let r=0;r<p.m.length;r++)for(let col=0;col<p.m[r].length;col++)if(p.m[r][col]&&p.y+r>=0)block(c,x+(p.x+col)*cell,y+(p.y+r)*cell,cell,p.m[r][col])}
   text(c,'下一块',252,42,15);preview(c,g.queue[0],255,65);text(c,'暂存 · C',252,159,15);preview(c,g.hold,255,183);text(c,'第 '+(Math.floor(g.lines/10)+1)+' 级',252,276,16);text(c,'空格 直接落底',252,307,12);text(c,'↑ 旋转 / Z 反转',252,332,12);pig(c,339,392,73,'pig')}
  if(id==='breakout'){sky(c,t.W,t.H);g.bricks.forEach(br=>{if(!br.hp)return;roundRect(c,br.x,br.y,br.w,br.h,6,palette[br.row]);text(c,br.hp>1?'••':'·',br.x+br.w/2,br.y+15,14,'rgba(66,78,63,.5)','center')});g.drops.forEach(d=>{roundRect(c,d.x-12,d.y-8,24,16,5,'#83b790');text(c,'↔',d.x,d.y+4,15,'#fff','center')});roundRect(c,g.paddle.x-g.paddle.w/2,g.paddle.y,g.paddle.w,g.paddle.h,7,g.wide?'#6ca580':'#bb7e95');c.fillStyle='#fff';c.beginPath();c.arc(g.ball.x,g.ball.y,g.ball.r,0,7);c.fill();c.strokeStyle='#b37591';c.lineWidth=2;c.stroke();text(c,'牧场 '+g.round+' / 3',24,26,13);if(g.waiting&&t.started)text(c,'点击或空格发球',380,279,18,'#7e8e73','center');pig(c,g.paddle.x,g.paddle.y-28,38)}
  if(id==='flappy'){sky(c,t.W,t.H);c.fillStyle='#d1dfa7';c.fillRect(0,g.ground,t.W,30);for(const p of g.pipes){const top=p.cy-g.gap/2,bottom=p.cy+g.gap/2;roundRect(c,p.x,0,p.w,top,8,'#96b9a0');roundRect(c,p.x-5,top-20,p.w+10,20,6,'#7ba88a');roundRect(c,p.x,bottom,p.w,g.ground-bottom,8,'#96b9a0');roundRect(c,p.x-5,bottom,p.w+10,20,6,'#7ba88a')}c.save();c.translate(g.x,g.y);c.rotate(Math.max(-.35,Math.min(.65,g.vy/800)));c.scale(-1,1);pig(c,0,0,56);const flap=Math.sin(performance.now()/70)*.35*(g.vy<0?1.6:.6);c.fillStyle='#fffdf8';c.strokeStyle='#e2cdbf';c.lineWidth=1.6;c.beginPath();c.ellipse(6,-6,15,7.5,-.35+flap,0,7);c.fill();c.stroke();c.beginPath();c.ellipse(10,-4,10,5,-.1+flap,0,7);c.fill();c.restore();text(c,String(g.score),380,48,34,'#6f9273','center')}
  if(id==='stack'){sky(c,t.W,t.H,true);const height=26,base=408,offset=Math.max(0,g.layers.length-10)*height;g.layers.forEach((l,i)=>{if(i<g.layers.length-17)return;const y=base-i*height+offset;roundRect(c,l.x,y,l.w,height-2,5,palette[i%palette.length]);c.fillStyle='rgba(255,255,255,.35)';c.fillRect(l.x+5,y+4,Math.max(0,l.w-10),3)});const y=base-g.layers.length*height+offset;g.cuts.forEach(cut=>{c.save();c.translate(cut.x+cut.w/2,y+cut.y);c.rotate(cut.angle);roundRect(c,-cut.w/2,0,cut.w,height-2,4,'#f0acba');c.restore()});if(!g.over){roundRect(c,g.active.x,y,g.active.w,height-2,5,palette[g.layers.length%palette.length]);pig(c,g.active.x+g.active.w/2,y-19,48)}text(c,g.score+' 层',32,44,25);text(c,g.streak>=2?'完美连击 ×'+g.streak:'看准重叠，再轻轻放下',568,44,14,'#8f83a0','right')}
 }
 function block(c,x,y,size,v){roundRect(c,x+1,y+1,size-2,size-2,4,palette[v-1]);c.fillStyle='rgba(255,255,255,.42)';c.fillRect(x+4,y+4,size-8,2);c.fillStyle='rgba(89,70,71,.48)';c.beginPath();c.arc(x+size*.33,y+size*.43,.8,0,7);c.arc(x+size*.67,y+size*.43,.8,0,7);c.fill();c.fillStyle='rgba(255,244,235,.5)';c.beginPath();c.ellipse(x+size/2,y+size*.66,size*.2,size*.13,0,0,7);c.fill();c.fillStyle='rgba(89,70,71,.4)';c.fillRect(x+size*.43,y+size*.64,1,1.5);c.fillRect(x+size*.57,y+size*.64,1,1.5)}
 function preview(c,type,x,y){roundRect(c,x-4,y-12,151,77,10,'#fffaf3');if(!type){text(c,'暂存一只小猪吧',x+7,y+31,11,'#9caa90');return}A.SHAPES[type].forEach((r,i)=>r.forEach((v,j)=>{if(v)block(c,x+j*21+15,y+i*21,21,v)}))}
 function keyDown(e){const {game:id,paused}=get();if(!has(id))return false;const k=e.key.toLowerCase(),dir={arrowleft:'left',a:'left',arrowright:'right',d:'right',arrowup:'up',w:'up',arrowdown:'down',s:'down'}[k];
  if(id==='connect'&&/^[1-7]$/.test(k)){e.preventDefault();dropConnect(+k-1);return true}
  let a=null;if(id==='blocks'){a={left:'left',right:'right',up:'rotate',down:'soft'}[dir]||{' ':'drop',z:'reverse',c:'hold',shift:'hold'}[k]}
  if(id==='breakout')a=(dir==='left'||dir==='right')?dir:k===' '?'launch':null;
  if(id==='flappy'&&(k===' '||dir==='up'))a='flap';if(id==='stack'&&(k===' '||dir==='down'))a='drop';if(id==='sokoban')a=dir||(k==='z'?'undo':null);if(id==='lights'&&k==='z')a='undo';
  if(!a)return false;e.preventDefault();if(paused)return true;if((id==='blocks'||id==='breakout')&&['left','right','soft'].includes(a)){if(!e.repeat){keys.add(a);s().repeat=-70;action(a)}}else if(!e.repeat||id==='sokoban')action(a);return true
 }
 function keyUp(e){const k=e.key.toLowerCase(),a={arrowleft:'left',a:'left',arrowright:'right',d:'right',arrowdown:'soft',s:'soft'}[k];if(a)keys.delete(a)}
 function changeLook(){sprites=[];if(has(get().game)){const id=get().game;if(id==='connect')renderConnect();if(id==='sokoban')renderSoko();if(id==='match')Match.changeLook();draw()}}
 return {has,init,tick,resize,keyDown,keyUp,changeLook,clearKeys:()=>keys.clear()}
}
root.PigArcadeUI={configs,create};
})(typeof window!=='undefined'?window:globalThis);
