/* Challenge games. Design references: flashhawk/spp.js fruitNinja collision
 * and blade lifetime; selenebun/bullethell normalized movement, hitbox and
 * invulnerability; alpiex1336-code/Rhythm-Game-v2 audio transport and holds.
 * MIT notices and pinned source links are shipped in assets/licenses/. */
(function(root){
'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function segmentCircle(a,b,p,r){const dx=b.x-a.x,dy=b.y-a.y,length=dx*dx+dy*dy,u=length?clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/length,0,1):0;return (a.x+u*dx-p.x)**2+(a.y+u*dy-p.y)**2<=r*r}
class Slice{
 constructor(mode,rng){this.mode=mode||'classic';this.rng=rng||Math.random;this.W=760;this.H=460;this.time=0;this.items=[];this.parts=[];this.sparkles=[];this.labels=[];this.trail=[];this.score=0;this.lives=3;this.missed=0;this.bestCombo=0;this.stroke=0;this.strokeHits=0;this.serial=0;this.spawnAt=.45;this.slow=0;this.over=false;this.won=false;this.limit=60}
 beginStroke(){this.stroke++;this.strokeHits=0;this.trail=[]}
 launch(kind,x,vx,vy){const item={id:++this.serial,kind:kind||'pig',x:x===undefined?100+this.rng()*560:x,y:this.H+45,vx:vx===undefined?(this.W/2-(x||this.W/2))*.15+(this.rng()-.5)*130:vx,vy:vy===undefined?-640-this.rng()*100:vy,r:kind==='bomb'?25:33,role:Math.floor(this.rng()*6),angle:0,spin:(this.rng()-.5)*2,cut:false};this.items.push(item);return item}
 wave(){const count=2+Math.floor(this.rng()*3)+(this.mode==='expert'?1:0),center=140+this.rng()*480;for(let k=0;k<count;k++)this.launch(this.rng()<.07?'gold':this.rng()<.06?'ice':'pig',clamp(center+(k-(count-1)/2)*70,65,695));if(this.time>3&&this.rng()<(this.mode==='expert'?.65:.32))this.launch('bomb',100+this.rng()*560);this.spawnAt=this.time+Math.max(.6,1.55-this.time*.008)+(this.rng()*.35)}
 slice(a,b){if(this.over)return [];const events=[];if(Math.hypot(b.x-a.x,b.y-a.y)<3)return events;this.trail.push({...a,life:.2},{...b,life:.2});for(const item of this.items){if(item.cut||!segmentCircle(a,b,item,item.r))continue;item.cut=true;if(item.kind==='bomb'){if(this.mode==='zen')this.score=Math.max(0,this.score-80);else this.lives--;this.strokeHits=0;events.push({type:'bomb',item});this.labels.push({x:item.x,y:item.y,text:this.mode==='zen'?'−80':'小心黑刺球！',life:1.1});if(this.lives<=0)this.over=true;continue}this.strokeHits++;this.bestCombo=Math.max(this.bestCombo,this.strokeHits);const bonus=this.strokeHits>=3?this.strokeHits*3:0,points=(item.kind==='gold'?30:10)+bonus;this.score+=points;if(item.kind==='ice')this.slow=3;events.push({type:'cut',item,combo:this.strokeHits,points});this.labels.push({x:item.x,y:item.y,text:this.strokeHits>=3?'连切 ×'+this.strokeHits+'  +'+points:'+'+points,life:.8});for(const side of [-1,1])this.parts.push({...item,side,vx:item.vx+side*110,vy:-95,life:.65});for(let k=0;k<10;k++)this.sparkles.push({x:item.x,y:item.y,vx:(this.rng()-.5)*280,vy:-this.rng()*220,life:.55,color:item.role})}this.items=this.items.filter(i=>!i.cut);return events}
 update(dt){if(this.over)return [];dt=clamp(dt,0,.08);this.time+=dt;this.slow=Math.max(0,this.slow-dt);const physics=dt*(this.slow?.48:1),events=[];if(this.time>=this.spawnAt)this.wave();for(const item of this.items){item.x+=item.vx*physics;item.y+=item.vy*physics;item.vy+=800*physics;item.angle+=item.spin*physics;if(item.y>this.H+80&&item.vy>0){item.cut=true;if(item.kind!=='bomb'&&this.mode!=='zen'){this.missed++;this.lives--;events.push({type:'miss'});if(this.lives<=0)this.over=true}}}this.items=this.items.filter(i=>!i.cut);for(const list of [this.parts,this.sparkles])for(const p of list){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=600*dt;p.life-=dt;if(p.angle!==undefined)p.angle+=p.side*dt*2}this.parts=this.parts.filter(p=>p.life>0);this.sparkles=this.sparkles.filter(p=>p.life>0);for(const l of this.labels){l.life-=dt;l.y-=25*dt}this.labels=this.labels.filter(l=>l.life>0);this.trail.forEach(p=>p.life-=dt);this.trail=this.trail.filter(p=>p.life>0).slice(-40);if(this.mode==='zen'&&this.time>=this.limit){this.over=true;this.won=true}return events}
}
class Shooter{
 constructor(hard,rng){this.rng=rng||Math.random;this.hard=!!hard;this.W=760;this.H=460;this.time=0;this.player={x:380,y:380,r:6};this.hp=3;this.score=0;this.kills=0;this.graze=0;this.bullets=[];this.shots=[];this.enemies=[];this.drops=[];this.parts=[];this.stage=1;this.bossKills=0;this.invuln=0;this.shield=0;this.cooldown=0;this.fireAt=0;this.waveAt=1;this.bossAt=24;this.boss=null;this.over=false;this.won=false}
 aim(x,y){this.player.x=clamp(x,28,this.W-28);this.player.y=clamp(y,100,this.H-25)}
 pulse(){if(this.over||this.cooldown>0)return false;this.cooldown=9;this.shield=1.3;this.score+=this.bullets.length*2;this.bullets=[];if(this.boss)this.boss.hp-=8;return true}
 hit(){if(this.invuln>0||this.shield>0)return false;this.hp--;this.invuln=1.5;if(this.hp<=0)this.over=true;return true}
 firePattern(source,count,spread,speed,offset){const base=Math.atan2(this.player.y-source.y,this.player.x-source.x)+(offset||0);for(let k=0;k<count;k++){const a=base+(k-(count-1)/2)*spread;this.bullets.push({x:source.x,y:source.y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,r:5,grazed:false,color:this.stage%3})}}
 spawnWave(){for(let k=0;k<3+this.stage;k++){const x=65+k*(630/(2+this.stage));this.enemies.push({x,y:-45-k%2*40,base:x,age:0,hp:2+this.stage,r:20,fire:1.4+k*.1})}this.waveAt=this.time+4.8-this.stage*.45}
 update(dt,dx,dy,focus){if(this.over)return [];dt=clamp(dt,0,.05);const events=[];this.time+=dt;this.invuln=Math.max(0,this.invuln-dt);this.shield=Math.max(0,this.shield-dt);this.cooldown=Math.max(0,this.cooldown-dt);const norm=Math.hypot(dx||0,dy||0)||1,speed=focus?145:310;this.aim(this.player.x+(dx||0)/norm*speed*dt,this.player.y+(dy||0)/norm*speed*dt);
  this.fireAt-=dt;if(this.fireAt<=0){this.fireAt=.16;for(const offset of [-9,9])this.shots.push({x:this.player.x+offset,y:this.player.y-24,vy:-650,r:4});events.push('shoot')}
  if(!this.boss&&this.time>=this.bossAt){this.boss={x:380,y:72,hp:70+this.stage*35,max:70+this.stage*35,r:42,fire:.8,age:0};this.enemies=[];events.push('boss')}else if(!this.boss&&this.time>=this.waveAt)this.spawnWave();
  for(const e of this.enemies){e.age+=dt;e.y+=38*dt;e.x=e.base+Math.sin(e.age*1.8)*45;e.fire-=dt;if(e.fire<=0){this.firePattern(e,this.hard?3:1,.19,145+this.stage*18);e.fire=2.3-this.stage*.18}if(Math.hypot(e.x-this.player.x,e.y-this.player.y)<e.r+this.player.r&&this.hit())events.push('hit');if(e.y>this.H+35)e.hp=0}
  if(this.boss){const b=this.boss;b.age+=dt;b.x=380+Math.sin(b.age*.75)*220;b.fire-=dt;if(b.fire<=0){const phase=b.hp/b.max;if(phase>.6)this.firePattern(b,this.hard?7:5,.17,145+this.stage*20);else if(phase>.3){const count=this.hard?18:12;for(let k=0;k<count;k++){const a=k*Math.PI*2/count+b.age*.35;this.bullets.push({x:b.x,y:b.y,vx:Math.cos(a)*150,vy:Math.sin(a)*150,r:5,grazed:false,color:1})}}else this.firePattern(b,9,.13,190,this.hard?Math.sin(b.age)*.4:0);b.fire=this.hard?.7:1}}
  for(const shot of this.shots){const old=shot.y;shot.y+=shot.vy*dt;for(const e of this.boss?[...this.enemies,this.boss]:this.enemies){if(e.hp>0&&segmentCircle({x:shot.x,y:old},shot,e,e.r+shot.r)){e.hp--;shot.dead=true;break}}}
  for(const e of this.enemies)if(e.hp<=0&&!e.counted){e.counted=true;if(e.y<this.H){this.score+=100;this.kills++;events.push('pop');if(this.kills%12===0)this.drops.push({x:e.x,y:e.y,r:12})}}
  this.enemies=this.enemies.filter(e=>e.hp>0);this.shots=this.shots.filter(s=>!s.dead&&s.y>-20);
  for(const b of this.bullets){const old={x:b.x,y:b.y};b.x+=b.vx*dt;b.y+=b.vy*dt;if(segmentCircle(old,b,this.player,b.r+this.player.r)){if(this.hit())events.push('hit');b.dead=true}else if(!b.grazed&&Math.hypot(b.x-this.player.x,b.y-this.player.y)<26){b.grazed=true;this.graze++;this.score+=5;events.push('graze')}}this.bullets=this.bullets.filter(b=>!b.dead&&b.x>-30&&b.x<this.W+30&&b.y>-40&&b.y<this.H+30);
  this.drops=this.drops.filter(d=>{d.y+=80*dt;if(Math.hypot(d.x-this.player.x,d.y-this.player.y)<30){this.hp=Math.min(3,this.hp+1);this.score+=150;events.push('heal');return false}return d.y<this.H+20});
  if(this.boss&&this.boss.hp<=0){this.bossKills++;this.score+=1500*this.stage;this.bullets=[];this.boss=null;this.hp=Math.min(3,this.hp+1);this.cooldown=0;events.push('bossWin');if(this.stage>=3){this.over=true;this.won=true}else{this.stage++;this.waveAt=this.time+2;this.bossAt=this.time+24}}
  return events}
}
// Authored procedural four-lane chart: no adjacent tap intrudes into a hold.
function chart(level){const hard=level==='hard',easy=level==='easy',bpm=easy?104:hard?148:124,beat=60/bpm,bars=easy?16:hard?24:20,notes=[],busy=Array(4).fill(0);let id=0;for(let b=4;b<bars*4;b++){const lane=(b*3+Math.floor(b/8))%4,t=b*beat;if(t>=busy[lane]){const hold=!easy&&b%12===6?beat*(hard?2:1.5):0;notes.push({id:++id,lane,t,end:t+hold,hold,done:false,started:false});busy[lane]=t+hold+beat*.4}if(hard&&b%4===1){const l=(lane+2)%4;if(t>=busy[l])notes.push({id:++id,lane:l,t,end:t,hold:0,done:false,started:false})}if(!easy&&b%8===3){const l=(lane+1)%4,at=t+beat*.5;if(at>=busy[l])notes.push({id:++id,lane:l,t:at,end:at,hold:0,done:false,started:false})}}notes.sort((a,b)=>a.t-b.t||a.lane-b.lane);return {bpm,beat,notes,duration:bars*4*beat+1}}
class Rhythm{
 constructor(level){Object.assign(this,chart(level||'normal'));this.time=0;this.offset=0;this.score=0;this.combo=0;this.maxCombo=0;this.health=100;this.perfect=0;this.good=0;this.miss=0;this.pressed=new Set();this.over=false;this.won=false;this.feedback=[];this.lastBeat=-1;this.window=.15}
 judgement(n,kind,tail){const points=kind==='perfect'?100:kind==='good'?65:0;if(kind==='miss'){this.miss++;this.combo=0;this.health=Math.max(0,this.health-9)}else{this[kind]++;this.combo++;this.maxCombo=Math.max(this.combo,this.maxCombo);this.health=Math.min(100,this.health+2);this.score+=points+Math.min(50,this.combo*2)}if(tail||!n.hold||kind==='miss')n.done=true;else n.started=true;const ev={type:kind,lane:n.lane,tail:!!tail,at:this.time};this.feedback.push(ev);return ev}
 press(lane,offset){if(this.over||this.pressed.has(lane))return null;this.pressed.add(lane);const at=this.time+(offset===undefined?this.offset:offset),n=this.notes.find(n=>n.lane===lane&&!n.done&&!n.started&&Math.abs(n.t-at)<=this.window);if(!n)return {type:'empty',lane};return this.judgement(n,Math.abs(n.t-at)<=.055?'perfect':'good',false)}
 release(lane){this.pressed.delete(lane);const n=this.notes.find(n=>n.lane===lane&&n.started&&!n.done);if(!n)return null;return this.judgement(n,this.time+this.offset>=n.end-.1?'perfect':'miss',true)}
 updateTo(time){if(this.over)return [];this.time=Math.max(this.time,time);const at=this.time+this.offset,events=[];for(const n of this.notes){if(n.done)continue;if(n.started&&at>=n.end){events.push(this.judgement(n,this.pressed.has(n.lane)?'perfect':'miss',true))}else if(!n.started&&at>n.t+this.window)events.push(this.judgement(n,'miss',false))}const beat=Math.floor(this.time/this.beat);if(beat>this.lastBeat){this.lastBeat=beat;events.push({type:'beat',beat})}this.feedback=this.feedback.filter(f=>this.time-f.at<.65);if(this.health<=0||this.time>=this.duration){this.over=true;this.won=this.health>0}return events}
 get accuracy(){return this.perfect+this.good+this.miss?Math.round((this.perfect+this.good*.65)/(this.perfect+this.good+this.miss)*100):100}
}
const api={segmentCircle,Slice,Shooter,Rhythm,chart};if(typeof module!=='undefined')module.exports=api;root.PigChallengeCore=api;
})(typeof window!=='undefined'?window:globalThis);
