(function(root){
'use strict';
const A=root.PigChallengeCore;
const configs={
 slice:{name:'切切猪',icon:'i-slice',title:'划一道光，猪猪软糖啵啵开。',subtitle:'像切西瓜一样，把飞起来的软糖猪猪一划两半。连切越多，哼唧越开心。',tag:'轨迹切割 · 连切 / 金猪 / 冰猪',eyebrow:'15 / PIGGY SLICES',note:'飞起来的小猪是软糖，黑色带尖刺的是危险球。',levels:[['classic','经典 · 三次失误'],['zen','60 秒冲分'],['expert','高手 · 密集出场']],labels:['本局得分','生命 / 时间','最高得分'],tips:[['按住，再划过去','鼠标按住左键拖动，或手指划过画面；一条轨迹可切中多只。键盘可按住空格配合方向键 / WASD 移动光刃。'],['一划多只，连切加分','同一划切到三只起有额外分。金猪加分更多，蓝色冰猪会让飞行暂时变慢。'],['绕开黑刺球','经典和高手模式：漏掉小猪或切中黑刺球扣生命。60 秒模式不计漏切，黑刺球扣 80 分。']]},
 shooter:{name:'猪猪星际守卫',icon:'i-ship',title:'小小宇航猪，守住星光牧场。',subtitle:'穿过弹幕的空隙，接住星星补给，挑战三位会变换招式的云朵首领。',tag:'弹幕射击 · 小判定 / 擦弹 / 三位首领',eyebrow:'16 / STARRY GUARD',note:'白色小点是实际判定位置；按 Shift 慢移，空格开启清弹护盾。',levels:[['easy','星光巡航'],['hard','弹幕挑战']],labels:['本局得分','剩余生命','最高得分'],tips:[['移动，自动发射星光','方向键 / WASD、拖动画面或屏幕按钮移动，小猪自动射击。Shift 慢速移动，适合穿窄缝。'],['清弹护盾，九秒恢复','空格 / 护盾按钮清掉当前弹幕并短暂保护小猪。受击后也有短暂无敌；绿色星星补一条生命。'],['看招式，找空隙','三位首领随血量切换扇形、环形和瞄准弹。擦过弹幕额外加分；小猪中央的小点碰到弹幕才算受击。']]},
 rhythm:{name:'猪猪节奏派对',icon:'i-rhythm',title:'跟着节拍，小蹄子一起落下。',subtitle:'四条彩色跑道，单点、双点和长按。听见猪猪合唱，也练出更稳的节奏。',tag:'节奏挑战 · 单点 / 长按 / 双键 / 准确率',eyebrow:'17 / LITTLE BEATS',note:'使用音频时钟同步；可以调节判定偏移，暂停后从原节拍继续。',levels:[['easy','小步舞 · 104 BPM'],['normal','快乐舞 · 124 BPM'],['hard','飞蹄舞 · 148 BPM']],labels:['本局得分','连击 / 准确率','最高得分'],tips:[['到白线时按下','四列依次为 D F J K，或 ← ↓ ↑ →。也可点 / 按住画面下方的四个按钮。'],['长条要按到尾端','长按音符头到线时按住，尾部过线再松开；暂停后重新按住。挑战档会有双键和半拍，过早松开算漏拍。'],['稳住连击与体力','完美判定窗口更窄，准确有较宽容窗口；漏拍减少体力。完成曲目即过关，连击和准确率决定等级。']]}
};
function create(ui){const {$,Sound,Store,icon,message,stats,record,result,confetti}=ui,get=ui.get,s=()=>get().state;let keys=new Set(),sprites={};const has=id=>!!configs[id];
 const colors=['#ef7592','#efc456','#73c48e','#69b9e8','#b18ce2','#edaa68'];
 function text(c,str,x,y,size,color,align){c.font='700 '+(size||16)+'px "Microsoft YaHei",sans-serif';c.fillStyle=color||'#ecf4fa';c.textAlign=align||'left';c.fillText(str,x,y);c.textAlign='left'}
 function disk(c,x,y,r,color){c.fillStyle=color;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill()}
 function pig(c,x,y,size,role,rotation,half){const key=role||'pig';let im=sprites[key];if(!im){im=new Image();im.src=ui.pigSrc(key);sprites[key]=im}c.save();c.translate(x,y);c.rotate(rotation||0);if(half){c.beginPath();c.rect(half<0?-size/2:0,-size/2,size/2,size);c.clip()}if(im.complete&&im.naturalWidth)c.drawImage(im,-size/2,-size/2,size,size);c.restore()}
 function status(){const {game:id,state:t}=get(),g=t.g;if(id==='slice')stats(g.score,g.mode==='zen'?Math.max(0,Math.ceil(60-g.time))+' s':'♥ '.repeat(Math.max(0,g.lives)));if(id==='shooter')stats(g.score,'♥ '.repeat(Math.max(0,g.hp)));if(id==='rhythm')stats(g.score,g.combo+' / '+g.accuracy+'%')}
 function finish(){const t=s(),g=t.g;if(t.finished)return;t.finished=true;keys.clear();status();record(g.score);Sound.stop();if(g.won){Sound.win();confetti(40)}else Sound.lose();const id=get().game;result(id==='slice'?'软糖派对收工啦！':id==='shooter'?(g.won?'星光牧场守住啦！':'宇航猪回来休息啦。'):g.won?'猪猪舞会谢幕！':'小蹄子歇一歇。',id==='slice'?'本局 '+g.score+' 分，最高一划连切 '+g.bestCombo+' 只。':id==='shooter'?'本局 '+g.score+' 分，击退 '+g.bossKills+' 位首领，擦弹 '+g.graze+' 次。':'本局 '+g.score+' 分，准确率 '+g.accuracy+'%，最高连击 '+g.maxCombo+'；完美 '+g.perfect+'，准确 '+g.good+'，漏拍 '+g.miss+'。',g.won)}
 function start(){const t=s();if(get().paused||t.finished)return false;if(!t.started){t.started=true;ui.setRunning(true);$('challenge-start').hidden=true;Sound.greet();t.audioAnchor=Sound.ctx?Sound.ctx.currentTime:0;t.clockAnchor=0;message(get().game==='rhythm'?'先听四拍，再跟着白线按 D F J K。':'出发！')}return true}
 function coord(e){const t=s(),r=t.cv.getBoundingClientRect();return {x:(e.clientX-r.left)/r.width*t.W,y:(e.clientY-r.top)/r.height*t.H}}
 function init(id){keys.clear();const t={started:false,finished:false,W:760,H:460,cursor:{x:380,y:240},pointer:null,clockPaused:false};ui.setState(t);const level=get().level;t.g=id==='slice'?new A.Slice(level):id==='shooter'?new A.Shooter(level==='hard'):new A.Rhythm(level);$('board').innerHTML='<div class="canvas-wrap challenge-canvas"><canvas id="challenge-canvas" tabindex="0" aria-label="'+configs[id].name+'画面"></canvas><div id="challenge-start" class="start-overlay"><button class="primary" id="challenge-go">'+icon('i-play','sm')+'开始挑战</button><small>'+ (id==='rhythm'?'D F J K / 方向键 / 下方按钮':'点击开始，准备小蹄子')+'</small></div></div><div id="challenge-controls" class="challenge-controls"></div>';t.cv=$('challenge-canvas');t.ctx=t.cv.getContext('2d');$('challenge-go').onclick=start;
  if(id==='slice'){$('challenge-controls').innerHTML='<span class="muted">点一下就能切中小猪 · 按住划过去可一划多只 · 避开黑刺球</span>';t.cv.onpointerdown=e=>{if(e.button>0||!start())return;e.preventDefault();t.cv.focus({preventScroll:true});t.pointer=e.pointerId;t.cursor=coord(e);t.g.beginStroke();try{t.cv.setPointerCapture(e.pointerId)}catch(err){}const c=t.cursor;cut({x:c.x-24,y:c.y+18},{x:c.x+24,y:c.y-18})};t.cv.onpointermove=e=>{if(t.pointer!==e.pointerId||get().paused)return;const p=coord(e);cut(t.cursor,p);t.cursor=p};t.cv.onpointerup=t.cv.onpointercancel=()=>t.pointer=null}
  if(id==='shooter'){$('challenge-controls').innerHTML='<div class="shooter-pad">'+ui.dpadHTML()+'<button class="primary" data-challenge="shield">清弹护盾 · 空格</button><span id="shield-status">护盾就绪</span></div>';for(const b of document.querySelectorAll('#challenge-controls [data-dir]')){b.onpointerdown=e=>{e.preventDefault();if(!start())return;keys.add(b.dataset.dir);try{b.setPointerCapture(e.pointerId)}catch(err){}};b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.dir);b.onclick=e=>{if(e.detail===0&&start()){const d=b.dataset.dir;t.g.aim(t.g.player.x+(d==='right'?25:d==='left'?-25:0),t.g.player.y+(d==='down'?25:d==='up'?-25:0))}}}document.querySelector('[data-challenge="shield"]').onclick=()=>{if(start()&&t.g.pulse())Sound.starShield()};t.cv.onpointerdown=e=>{if(e.button>0||!start())return;e.preventDefault();t.pointer=e.pointerId;try{t.cv.setPointerCapture(e.pointerId)}catch(err){}const p=coord(e);t.glide=p;t.down=p};t.cv.onpointermove=e=>{if(t.pointer!==e.pointerId||get().paused)return;const p=coord(e);if(t.down&&Math.hypot(p.x-t.down.x,p.y-t.down.y)<10)return;t.down=null;t.glide=null;t.g.aim(p.x,p.y)};t.cv.onpointerup=t.cv.onpointercancel=()=>t.pointer=null}
  if(id==='rhythm'){t.offset=Store.get('rhythm-offset',0);t.g.offset=-t.offset/1000;t.g.assist=Store.get('rhythm-assist',true);$('play-toolbar').innerHTML='<button class="mode" id="rhythm-assist" aria-pressed="'+t.g.assist+'" title="开启后：长条点一下即可保持到尾端，双键点其中一个即可">单击模式 '+(t.g.assist?'开':'关')+'</button><label class="rhythm-offset">判定偏移 <input id="rhythm-offset" type="range" min="-150" max="150" step="10" value="'+t.offset+'"><output id="rhythm-offset-value">'+t.offset+' ms</output></label><span class="key-hint">正值：按键比音符晚一些 · 负值：早一些</span>';$('rhythm-assist').onclick=e=>{t.g.assist=!t.g.assist;Store.set('rhythm-assist',t.g.assist);e.currentTarget.setAttribute('aria-pressed',t.g.assist);e.currentTarget.textContent='单击模式 '+(t.g.assist?'开':'关');Sound.click();message(t.g.assist?'单击模式：长条点一下会自动保持到尾端，双键只要点其中一个。':'挑战模式：长条要按住到尾端，双键要同时按下。')};$('rhythm-offset').oninput=e=>{t.offset=+e.target.value;t.g.offset=-t.offset/1000;Store.set('rhythm-offset',t.offset);$('rhythm-offset-value').textContent=t.offset+' ms'};$('challenge-controls').innerHTML='<div class="rhythm-keys">'+['D / ←','F / ↓','J / ↑','K / →'].map((k,i)=>'<button class="rhythm-key lane'+i+'" data-lane="'+i+'" aria-label="节奏第 '+(i+1)+' 轨 '+k+'">'+k+'<small>点按 / 长按</small></button>').join('')+'</div>';document.querySelectorAll('[data-lane]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();if(!start())return;try{b.setPointerCapture(e.pointerId)}catch(err){}rhythmPress(+b.dataset.lane)};b.onpointerup=b.onpointercancel=()=>rhythmRelease(+b.dataset.lane);b.onclick=e=>{if(e.detail===0&&start()){rhythmPress(+b.dataset.lane);rhythmRelease(+b.dataset.lane)}}})}
  resize();status();message(configs[id].note)}
 function cut(a,b){const t=s(),events=t.g.slice(a,b);if(!events.length)return;const cuts=events.filter(e=>e.type==='cut'),danger=events.some(e=>e.type==='bomb');if(cuts.length)Sound.sliceCut(cuts.length,t.g.strokeHits);if(danger)Sound.sliceDanger();status();if(t.g.over)finish()}
 function rhythmFeedback(ev){if(!ev)return;if(ev.type==='perfect'||ev.type==='good')Sound.rhythmHit(ev.lane,ev.type==='perfect',s().g.combo);else if(ev.type==='miss')Sound.rhythmMiss()}
 function rhythmPress(lane){if(get().paused||!start())return;const t=s();updateRhythmClock();rhythmFeedback(t.g.press(lane,-t.offset/1000));const b=document.querySelector('[data-lane="'+lane+'"]');if(b)b.classList.add('held');status()}
 function rhythmRelease(lane){if(get().game!=='rhythm'||get().paused)return;const t=s();if(!t||!t.started)return;updateRhythmClock();rhythmFeedback(t.g.release(lane));const b=document.querySelector('[data-lane="'+lane+'"]');if(b)b.classList.remove('held');status()}
 function updateRhythmClock(){const t=s();if(!t.started||get().paused||t.finished)return;const now=Sound.ctx?Sound.ctx.currentTime:get().elapsed/1000;if(t.clockPaused){t.audioAnchor=now;t.clockAnchor=t.g.time;t.clockPaused=false}const events=t.g.updateTo(t.clockAnchor+now-t.audioAnchor);for(const e of events)if(e.type==='beat'){Sound.rhythmBeat(e.beat,t.g.bpm);if(e.beat>0&&e.beat%16===0&&t.g.combo>0)Sound.voice(Math.floor(e.beat/16)%4,{gain:.3,rate:1.25,dur:.18})}else rhythmFeedback(e);if(t.g.over)finish()}
 function tick(dt){const {game:id,paused}=get();if(!has(id))return;const t=s(),g=t.g;if(!paused&&t.started&&!t.finished){if(id==='slice'){const old={...t.cursor},speed=700*dt/1000;t.cursor.x=Math.max(0,Math.min(t.W,t.cursor.x+(keys.has('right')?speed:0)-(keys.has('left')?speed:0)));t.cursor.y=Math.max(0,Math.min(t.H,t.cursor.y+(keys.has('down')?speed:0)-(keys.has('up')?speed:0)));if(keys.has('blade'))cut(old,t.cursor);const ev=g.update(dt/1000);if(ev.some(e=>e.type==='miss'))Sound.miss()}if(id==='shooter'){let mx=(keys.has('right')?1:0)-(keys.has('left')?1:0),my=(keys.has('down')?1:0)-(keys.has('up')?1:0);if(mx||my)t.glide=null;else if(t.glide){const dx=t.glide.x-g.player.x,dy=t.glide.y-g.player.y,d=Math.hypot(dx,dy);if(d<5)t.glide=null;else{const k=Math.min(1,d/(310*dt/1000));mx=dx/d*k;my=dy/d*k}}const ev=g.update(dt/1000,mx,my,keys.has('focus'));if(ev.includes('shoot'))Sound.starShot();if(ev.includes('pop'))Sound.starPop();if(ev.includes('hit'))Sound.starHit();if(ev.includes('boss')){Sound.milestone();message('第 '+g.stage+' 位云朵首领来了，观察空隙！')}if(ev.includes('bossWin'))Sound.gold();if(ev.includes('heal'))Sound.apple();$('shield-status').textContent=g.cooldown>0?'护盾 '+Math.ceil(g.cooldown)+' s':'护盾就绪'}if(id==='rhythm')updateRhythmClock();status();if(g.over)finish()}draw()}
 function resize(){if(!has(get().game))return;const t=s();if(!t||!t.cv)return;const host=t.cv.parentElement,r=host.parentElement.getBoundingClientRect(),height=Math.max(220,window.innerHeight-r.top-150),scale=Math.min((r.width||760)/760,height/460,1.1),w=Math.floor(760*scale),h=Math.floor(460*scale),dpr=Math.min(2,window.devicePixelRatio||1);t.cv.width=w*dpr;t.cv.height=h*dpr;t.cv.style.width=w+'px';t.cv.style.height=h+'px';host.style.width=w+'px';t.ctx.setTransform(scale*dpr,0,0,scale*dpr,0,0);draw()}
 function draw(){const {game:id}=get();if(!has(id))return;const t=s();if(!t||!t.ctx)return;const c=t.ctx,g=t.g;c.clearRect(0,0,760,460);const bg=c.createLinearGradient(0,0,0,460);bg.addColorStop(0,id==='slice'?'#f6e9db':'#202d44');bg.addColorStop(1,id==='slice'?'#e9ddca':'#38415c');c.fillStyle=bg;c.fillRect(0,0,760,460);
  if(id==='slice'){c.strokeStyle='rgba(137,111,82,.13)';c.lineWidth=2;for(let y=40;y<460;y+=70){c.beginPath();c.moveTo(0,y);c.lineTo(760,y);c.stroke()}for(const p of g.sparkles){c.globalAlpha=p.life/.55;disk(c,p.x,p.y,4,colors[p.color])}c.globalAlpha=1;for(const p of g.parts){c.globalAlpha=Math.min(1,p.life/.3);pig(c,p.x,p.y,84,['bow','crown','flower','space','wizard','bee'][p.role],p.angle,p.side)}c.globalAlpha=1;for(const item of g.items){if(item.kind==='bomb'){disk(c,item.x,item.y,25,'#394154');c.strokeStyle='#64728a';c.lineWidth=6;for(let k=0;k<8;k++){const a=k*Math.PI/4;c.beginPath();c.moveTo(item.x+Math.cos(a)*20,item.y+Math.sin(a)*20);c.lineTo(item.x+Math.cos(a)*34,item.y+Math.sin(a)*34);c.stroke()}text(c,'×',item.x,item.y+8,28,'#fff','center')}else{disk(c,item.x,item.y,38,item.kind==='gold'?'#f4d172':item.kind==='ice'?'#b2e7fa':colors[item.role]+'77');pig(c,item.x,item.y,87,['bow','crown','flower','space','wizard','bee'][item.role],item.angle);if(item.kind==='gold'||item.kind==='ice')text(c,item.kind==='gold'?'+30':'慢',item.x,item.y+45,14,item.kind==='gold'?'#906c25':'#3783a3','center')}}for(let k=1;k<g.trail.length;k++){const a=g.trail[k-1],b=g.trail[k];c.strokeStyle='rgba(255,255,255,'+Math.min(1,b.life/.2)+')';c.lineWidth=6*b.life/.2;c.lineCap='round';c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke()}g.labels.forEach(l=>text(c,l.text,l.x,l.y,23,'#a74c74','center'));text(c,g.mode==='zen'?'剩余 '+Math.max(0,Math.ceil(60-g.time))+' 秒':'最高连切 '+g.bestCombo+' 只',25,34,18,'#7c725f');if(g.slow)text(c,'冰猪减速 '+Math.ceil(g.slow)+' s',735,34,18,'#3885a1','right');if(keys.has('blade'))disk(c,t.cursor.x,t.cursor.y,5,'#fff')}
  if(id==='shooter'){for(let k=0;k<60;k++)disk(c,(k*127)%760,((k*79+g.time*15)%460),k%3===0?2:1,'#ffffff55');for(const shot of g.shots){c.strokeStyle='#baffd4';c.lineWidth=4;c.beginPath();c.moveTo(shot.x,shot.y);c.lineTo(shot.x,shot.y+14);c.stroke()}for(const e of g.enemies){disk(c,e.x,e.y,e.r,'#f0a8c4');pig(c,e.x,e.y,48,'pirate');}for(const b of g.bullets){disk(c,b.x,b.y,b.r+2,['#ffbe6c','#e799cc','#82d8ef'][b.color]);disk(c,b.x,b.y,2,'#fff')}for(const d of g.drops){disk(c,d.x,d.y,12,'#90e6b7');text(c,'+',d.x,d.y+5,17,'#254a47','center')}if(g.boss){const b=g.boss;disk(c,b.x,b.y,48,'#bca4e4');pig(c,b.x,b.y,100,'crown');c.fillStyle='#ffffff33';c.fillRect(200,15,360,7);c.fillStyle='#edbada';c.fillRect(200,15,360*Math.max(0,b.hp)/b.max,7);text(c,'云朵首领 '+g.stage,380,42,14,'#f2e1f2','center')}if(g.shield>0){disk(c,g.player.x,g.player.y,42,'#7cc9f566');c.strokeStyle='#9fddff';c.lineWidth=3;c.beginPath();c.arc(g.player.x,g.player.y,42,0,7);c.stroke()}if(!g.invuln||Math.floor(g.invuln*12)%2===0)pig(c,g.player.x,g.player.y,65,'space');disk(c,g.player.x,g.player.y,6,'#fff');disk(c,g.player.x,g.player.y,3,'#375d79');text(c,'第 '+g.stage+' 关 · 擦弹 '+g.graze,23,32,17)}
  if(id==='rhythm'){const left=160,width=440,lane=110,line=370,travel=240;for(let l=0;l<4;l++){c.fillStyle=colors[l]+'26';c.fillRect(left+l*lane,35,lane-5,380);if(g.pressed.has(l)){c.fillStyle=colors[l]+'66';c.fillRect(left+l*lane,35,lane-5,380)}text(c,['D','F','J','K'][l],left+l*lane+52,427,23,colors[l],'center')}c.strokeStyle='#fff';c.lineWidth=3;c.beginPath();c.moveTo(left-5,line);c.lineTo(left+width-2,line);c.stroke();for(const n of g.notes){if(n.done)continue;const x=left+n.lane*lane+53,y=line-(n.t-g.time)*travel;if(y<-120||y>430)continue;if(n.hold){const endY=line-(n.end-g.time)*travel;c.fillStyle=colors[n.lane]+'99';ui.rr(c,x-15,endY,30,Math.max(1,y-endY),8);c.fill();if(n.started)disk(c,x,line,22,'#fff7')}disk(c,x,y,23,colors[n.lane]);pig(c,x,y,48,['bow','flower','music','wizard'][n.lane]);}for(const f of g.feedback)text(c,f.type==='perfect'?'完美':f.type==='good'?'准确':'漏拍',left+f.lane*lane+53,330-(g.time-f.at)*35,18,f.type==='miss'?'#ee98ab':'#fff7b9','center');text(c,g.combo+' 连击',380,29,20,'#fff','center');c.fillStyle='#ffffff22';c.fillRect(27,82,14,280);c.fillStyle=g.health<30?'#ed8098':'#91d9b5';c.fillRect(27,362-g.health*2.8,14,g.health*2.8);text(c,'体力',34,64,12,'#fff','center');text(c,Math.max(0,Math.ceil(g.duration-g.time))+' s',706,42,17,'#fff','right');text(c,g.accuracy+'%',704,71,17,'#edcdeb','right');if(g.time<g.beat*4&&t.started)text(c,'预备 · '+(4-Math.floor(g.time/g.beat)),380,205,32,'#fff4bc','center')}
 }
 function keyDown(e){const id=get().game;if(!has(id))return false;const k=e.key.toLowerCase(),dir={arrowleft:'left',a:'left',arrowright:'right',d:'right',arrowup:'up',w:'up',arrowdown:'down',s:'down'}[k];if(id==='rhythm'){const lane={d:0,f:1,j:2,k:3,arrowleft:0,arrowdown:1,arrowup:2,arrowright:3}[k];if(lane===undefined&&k!==' ')return false;e.preventDefault();if(get().paused)return true;if(k===' ')start();else if(!e.repeat)rhythmPress(lane);return true}if(!dir&&![' ','shift'].includes(k))return false;e.preventDefault();if(get().paused||!start())return true;if(dir)keys.add(dir);if(id==='slice'&&k===' '&&!e.repeat){keys.add('blade');s().g.beginStroke()}if(id==='shooter'){if(k==='shift')keys.add('focus');if(k===' '&&!e.repeat&&s().g.pulse())Sound.starShield()}return true}
 function keyUp(e){const id=get().game,k=e.key.toLowerCase();if(id==='rhythm'){const lane={d:0,f:1,j:2,k:3,arrowleft:0,arrowdown:1,arrowup:2,arrowright:3}[k];if(lane!==undefined)rhythmRelease(lane)}const dir={arrowleft:'left',a:'left',arrowright:'right',d:'right',arrowup:'up',w:'up',arrowdown:'down',s:'down',shift:'focus',' ':'blade'}[k];if(dir)keys.delete(dir)}
 function clearKeys(){keys.clear();const t=s();if(t){t.pointer=null;if(t.g instanceof A.Rhythm){t.clockPaused=true;t.g.pressed.clear();document.querySelectorAll('.rhythm-key').forEach(b=>b.classList.remove('held'))}}}
 return {has,init,tick,resize,keyDown,keyUp,clearKeys,changeLook:()=>{sprites={};draw()}};
}
root.PigChallengeUI={configs,create};
})(typeof window!=='undefined'?window:globalThis);
