/* 4.1: special-pig match rules. Dual-axis scanning, intersections and special
 * geometry adapted from egnaro9/match3-engine (MIT, Erik Hill).
 * See assets/licenses/ and README for pinned upstream references. */
(function(root){
'use strict';
class Match3{
 constructor(colors,moves,target,rng,options){this.n=8;this.colors=colors||6;this.moves=moves||28;this.target=target||2400;this.rng=rng||Math.random;this.score=0;this.over=false;this.won=false;this.serial=0;this.specials=Array(64).fill(null);this.frost=Array(64).fill(0);this.collected=Array(this.colors).fill(0);this.collectGoal=options&&options.collect||null;if(options&&options.frost)options.frost.forEach(([i,n])=>this.frost[i]=n);this.newBoard()}
 random(){return Math.floor(this.rng()*this.colors)}
 snapshot(){return {board:this.board.slice(),specials:this.specials.slice(),tokens:this.tokens.slice(),frost:this.frost.slice(),score:this.score,moves:this.moves,collected:this.collected.slice()}}
 newBoard(){for(let attempt=0;attempt<80;attempt++){this.board=[];for(let i=0;i<64;i++){const choices=Array.from({length:this.colors},(_,k)=>k).filter(v=>!(i%8>=2&&this.board[i-1]===v&&this.board[i-2]===v)&&!(i>=16&&this.board[i-8]===v&&this.board[i-16]===v));this.board.push(choices[Math.floor(this.rng()*choices.length)])}this.tokens=Array.from({length:64},()=>++this.serial);if(this.findMove())return}this.board=Array.from({length:64},(_,i)=>(i%8+Math.floor(i/8)*2)%this.colors);this.board[0]=0;this.board[1]=1;this.board[2]=0;this.board[9]=0}
 // Close runs at the right/bottom sentinel as well as at a colour change.
 runs(){const out=[];for(const axis of ['row','col'])for(let line=0;line<8;line++){let start=0;for(let p=1;p<=8;p++){const prev=axis==='row'?line*8+p-1:(p-1)*8+line,at=axis==='row'?line*8+p:p*8+line;const same=p<8&&this.board[prev]>=0&&this.board[at]===this.board[prev]&&this.specials[prev]!=='rainbow'&&this.specials[at]!=='rainbow';if(same)continue;if(p-start>=3&&this.board[prev]>=0&&this.specials[prev]!=='rainbow')out.push({axis,ids:Array.from({length:p-start},(_,k)=>axis==='row'?line*8+start+k:(start+k)*8+line)});start=p}}return out}
 matches(){return [...new Set(this.runs().flatMap(r=>r.ids))]}
 adjacent(a,b){return Number.isInteger(a)&&Number.isInteger(b)&&a>=0&&a<64&&b>=0&&b<64&&(Math.abs(a-b)===8||(Math.floor(a/8)===Math.floor(b/8)&&Math.abs(a-b)===1))}
 exchange(a,b){for(const ar of [this.board,this.specials,this.tokens])[ar[a],ar[b]]=[ar[b],ar[a]]}
 findMove(){for(let i=0;i<64;i++)for(const j of [i+1,i+8]){if(!this.adjacent(i,j))continue;if(this.specials[i]||this.specials[j])return [i,j];this.exchange(i,j);const ok=this.matches().length;this.exchange(i,j);if(ok)return [i,j]}return null}
 creations(runs,preferred){const result=[],used=new Set();const group=[];for(const run of runs){const linked=group.filter(g=>g.ids.some(i=>run.ids.includes(i)));if(!linked.length)group.push({ids:run.ids.slice(),runs:[run]});else{const g=linked[0];g.ids=[...new Set([...g.ids,...run.ids])];g.runs.push(run);for(const other of linked.slice(1)){g.ids=[...new Set([...g.ids,...other.ids])];g.runs.push(...other.runs);group.splice(group.indexOf(other),1)}}}
  for(const g of group){const long=g.runs.find(r=>r.ids.length>=5);const cross=g.ids.find(i=>g.runs.filter(r=>r.ids.includes(i)).length>1);const four=g.runs.find(r=>r.ids.length===4);const kind=long?'rainbow':cross!==undefined?'bomb':four?four.axis:null;if(!kind)continue;const eligible=long?long.ids:cross!==undefined?[cross]:four.ids;let at=(preferred||[]).find(i=>eligible.includes(i)&&!this.specials[i]);if(at===undefined)at=eligible.find(i=>!this.specials[i]);if(at!==undefined&&!used.has(at)){result.push({index:at,kind});used.add(at)}}return result}
 area(i,radius){const r=Math.floor(i/8),c=i%8,out=[];for(let y=Math.max(0,r-radius);y<=Math.min(7,r+radius);y++)for(let x=Math.max(0,c-radius);x<=Math.min(7,c+radius);x++)out.push(y*8+x);return out}
 band(i,width){const r=Math.floor(i/8),c=i%8,out=[];for(let y=0;y<8;y++)for(let x=0;x<8;x++)if(Math.abs(y-r)<=width||Math.abs(x-c)<=width)out.push(y*8+x);return out}
 dominant(){const counts=Array(this.colors).fill(0);this.board.forEach(v=>{if(v>=0)counts[v]++});return counts.indexOf(Math.max(...counts))}
 expand(seed,targets,ignore){const ids=new Set(seed),effects=[],seen=new Set(ignore||[]),queue=[...ids];while(queue.length){const i=queue.shift(),kind=this.specials[i];if(!kind||seen.has(i))continue;seen.add(i);let extra=[];if(kind==='row')extra=Array.from({length:8},(_,c)=>Math.floor(i/8)*8+c);if(kind==='col')extra=Array.from({length:8},(_,r)=>r*8+i%8);if(kind==='bomb')extra=this.area(i,1);if(kind==='rainbow'){const color=targets&&targets[i]!==undefined?targets[i]:this.dominant();extra=this.board.map((v,k)=>v===color?k:-1).filter(k=>k>=0)}effects.push({index:i,kind});for(const j of extra)if(!ids.has(j)){ids.add(j);queue.push(j)}}return {ids:[...ids],effects}}
 combo(a,b){const sa=this.specials[a],sb=this.specials[b],out=[a,b],targets={};if(sa==='rainbow'||sb==='rainbow'){if(sa==='rainbow'&&sb==='rainbow')return {ids:Array.from({length:64},(_,i)=>i),targets,label:'双彩虹 · 全场派对'};const ri=sa==='rainbow'?a:b,other=ri===a?b:a,color=this.board[other],kind=this.specials[other];targets[ri]=color;this.board.forEach((v,i)=>{if(v===color){out.push(i);if(kind&&i!==ri)this.specials[i]=kind}});return {ids:[...new Set(out)],targets,label:kind?'彩虹组合 · 同色特技':'彩虹猪 · 同色全清'}}
  if(sa&&sb){if(sa==='bomb'&&sb==='bomb')return {ids:[...new Set([...out,...this.area(b,2)])],targets,ignore:[a,b],fx:[{kind:'bomb',index:b}],label:'双爆爆 · 5×5'};return {ids:[...new Set([...out,...this.band(b,sa==='bomb'||sb==='bomb'?1:0)])],targets,ignore:[a,b],fx:[{kind:'row',index:b},{kind:'col',index:b}],label:sa==='bomb'||sb==='bomb'?'火箭爆爆 · 三行三列':'双火箭 · 十字清场'}}return {ids:out.filter(i=>this.specials[i]),targets,label:'特殊猪出发'} }
 gravity(){const origins=new Map(this.tokens.map((v,i)=>[v,i])),drops=[];for(let c=0;c<8;c++){const live=[];for(let r=7;r>=0;r--){const i=r*8+c;if(this.board[i]>=0)live.push({v:this.board[i],s:this.specials[i],id:this.tokens[i]})}let spawn=0;for(let r=7;r>=0;r--){const i=r*8+c,entry=live[7-r];if(entry){this.board[i]=entry.v;this.specials[i]=entry.s;this.tokens[i]=entry.id;drops.push({token:entry.id,from:origins.get(entry.id),to:i})}else{this.board[i]=this.random();this.specials[i]=null;this.tokens[i]=++this.serial;drops.push({token:this.tokens[i],fromRow:-(++spawn),fromCol:c,to:i})}}}return drops}
 shuffle(){const special=this.specials.slice();this.newBoard();this.specials=special;return this.snapshot()}
 swap(a,b){if(this.over||!this.adjacent(a,b))return null;const before=this.snapshot();this.exchange(a,b);const special=!!(this.specials[a]||this.specials[b]);let runs=this.runs();if(!runs.length&&!special){this.exchange(a,b);return null}this.moves--;const swapped=this.snapshot(),frames=[];let gained=0,chain=0,first=special?this.combo(a,b):null,label=first?first.label:'';
  while((runs.length||first)&&chain<20){chain++;const created=first?[]:this.creations(runs,chain===1?[b,a]:null);const expanded=this.expand(first?first.ids:runs.flatMap(r=>r.ids),first&&first.targets,first&&first.ignore);if(first&&first.fx)expanded.effects.push(...first.fx);const keep=new Set(created.map(v=>v.index));const ids=expanded.ids.filter(i=>!keep.has(i));const frame={...this.snapshot(),ids,created,effects:expanded.effects,chain};for(const i of expanded.ids)if(this.frost[i]>0)this.frost[i]--;for(const i of ids){this.collected[this.board[i]]++;this.board[i]=-1;this.specials[i]=null}for(const v of created)this.specials[v.index]=v.kind;const points=ids.length*20*chain+created.length*100+expanded.effects.length*40;gained+=points;this.score+=points;frame.points=points;frame.drops=this.gravity();frame.after=this.snapshot();frames.push(frame);first=null;runs=this.runs()}
  let reshuffled=false;if(runs.length||!this.findMove()){this.shuffle();reshuffled=true}this.won=this.score>=this.target&&this.frost.every(v=>v===0)&&(!this.collectGoal||this.collected[this.collectGoal.color]>=this.collectGoal.count);this.over=this.won||this.moves<=0;return {before,swapped,frames,board:this.board.slice(),final:this.snapshot(),gained,chain,reshuffled,label,won:this.won,over:this.over}}
}
const api={Match3};if(typeof module!=='undefined')module.exports=api;root.PigMatchCore=api;
})(typeof window!=='undefined'?window:globalThis);
