/* Continuous swap -> clear -> gravity -> refill choreography.
 * Stable monotonic piece ids, inspired by match3-engine's browser-port notes;
 * cascade/feedback sequencing studied in candy-crush-match3 (MIT). */
(function(root){
'use strict';
const kinds=['ribbon','crown','leaf','diver','wizard','tiger'],names=['红蝴蝶结猪','金皇冠猪','绿叶猪','蓝潜水猪','紫魔法猪','橙小虎猪'];
const powers={row:['↔','横向火箭猪'],col:['↕','竖向火箭猪'],bomb:['✦','爆爆猪'],rainbow:['◎','彩虹猪']};
const src=k=>root.PIG_MATCH_URI&&root.PIG_MATCH_URI[k]||'assets/match/'+k+'.svg';
function create(ui,helpers){const {$,Sound,message,stats}=ui,get=ui.get,s=()=>get().state;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 function goals(v){const g=s().g,ice=v.frost.reduce((a,b)=>a+b,0),count=g.collectGoal;let html='<span>得分 <b>'+v.score+' / '+g.target+'</b></span>';if(g.frost.some(Boolean)||get().level!=='easy')html+='<span class="ice-goal">冰层 <b>'+ice+'</b></span>';if(count)html+='<span>收集 '+names[count.color]+' <b>'+Math.min(count.count,v.collected[count.color])+' / '+count.count+'</b></span>';$('match-objectives').innerHTML=html;stats(v.score,v.moves)}
 function init(){const t=s(),level=get().level,frost=[];if(level!=='easy')for(let r=2;r<=5;r++)for(let c=2;c<=5;c++)if(level==='hard'||r<5)frost.push([r*8+c,level==='hard'?2:1]);t.g=new root.PigMatchCore.Match3(level==='easy'?5:6,level==='hard'?30:28,{easy:2400,normal:3600,hard:5400}[level],null,{frost,collect:level==='easy'?null:{color:level==='hard'?5:2,count:level==='hard'?20:16}});t.started=true;t.selected=-1;t.pending=null;t.matchView=t.g.snapshot();ui.setRunning(true);$('play-toolbar').innerHTML='<div class="match-objectives" id="match-objectives"></div>'+helpers.button('hint','找一组交换');helpers.bindToolbar();$('board').innerHTML='<div class="match-legend">'+kinds.slice(0,t.g.colors).map((k,i)=>'<span><img src="'+src(k)+'" alt="">'+names[i].replace('猪','')+'</span>').join('')+'</div><div id="match-grid" class="match-grid" role="group" aria-label="消消乐棋盘"></div><div class="match-power-guide"><span><b>↔ / ↕ 火箭猪</b>四连，清一行或一列</span><span><b>✦ 爆爆猪</b>T / L 形，清周围九格</span><span><b>◎ 彩虹猪</b>五连，同色全清</span><span><b>特殊猪互换</b>发动组合技</span></div>';render(t.matchView);message('六种猪各有颜色与服饰。可点击交换，也可拖动一格；四连、五连会留下特殊猪。')}
 function render(v,phase,from,frame){const t=s(),box=$('match-grid');t.matchView=v;box.dataset.phase=phase||'idle';const size=box.clientWidth/8||45,positions=new Map((from&&from.tokens||[]).map((token,i)=>[token,{row:Math.floor(i/8),col:i%8}]));let html='';for(let i=0;i<64;i++)html+='<i class="match-slot" style="left:'+(i%8*12.5)+'%;top:'+(Math.floor(i/8)*12.5)+'%"></i>';
  for(let i=0;i<64;i++){const color=v.board[i],sp=v.specials[i];if(color<0)continue;const token=v.tokens[i],old=positions.get(token),drop=frame&&frame.drops.find(d=>d.token===token),row=Math.floor(i/8),col=i%8;let origin=old;if(drop)origin=drop.from!==undefined?{row:Math.floor(drop.from/8),col:drop.from%8}:{row:drop.fromRow,col:drop.fromCol};const moving=(phase==='swap'||phase==='return'||phase==='fall')&&origin&&(origin.row!==row||origin.col!==col),popping=phase==='clear'&&frame.ids.includes(i),making=phase==='clear'&&frame.created.some(c=>c.index===i);html+=`<button class="match-cell ${t.selected===i?'selected':''} ${t.hints&&t.hints.includes(i)?'hinted':''} ${moving?'moving':''} ${popping?'popping':''} ${making?'making':''}" data-match="${i}" data-token="${token}" data-special="${sp||''}" style="left:${col*12.5}%;top:${row*12.5}%;--dx:${origin?(origin.col-col)*size:0}px;--dy:${origin?(origin.row-row)*size:0}px;--move-time:${phase==='fall'?300:200}ms" aria-label="${row+1} 行 ${col+1} 列，${names[color]}${sp?'，'+powers[sp][1]:''}${v.frost[i]?'，冰层 '+v.frost[i]:''}" aria-pressed="${t.selected===i}"><span class="match-face type${color} ${sp?'special-'+sp:''}"><img src="${src(kinds[color])}" alt="" draggable="false"><i class="match-shape">${['●','▲','◆','■','★','✦'][color]}</i>${sp?'<b class="match-special">'+powers[sp][0]+'</b>':''}${making?'<em class="match-created">'+powers[frame.created.find(c=>c.index===i).kind][0]+'</em>':''}</span></button>`}
  v.frost.forEach((n,i)=>{if(n)html+='<span class="match-ice layer'+n+'" style="left:'+(i%8*12.5)+'%;top:'+(Math.floor(i/8)*12.5)+'%" aria-hidden="true"><small>'+n+'</small></span>'});if(phase==='clear'){for(const effect of frame.effects){html+='<i class="match-blast '+effect.kind+'" style="--col:'+effect.index%8+';--row:'+Math.floor(effect.index/8)+'" aria-hidden="true"></i>'}html+='<div class="match-float" aria-hidden="true">连锁 ×'+frame.chain+' <b>+'+frame.points+'</b></div>'}box.innerHTML=html;box.querySelectorAll('[data-match]').forEach(b=>{b.onclick=()=>{if(t.consumeClick){t.consumeClick=false;return}select(+b.dataset.match)};b.onpointerdown=e=>{if(t.pending||get().paused)return;t.swipe={index:+b.dataset.match,x:e.clientX,y:e.clientY};try{b.setPointerCapture(e.pointerId)}catch(err){}};b.onpointerup=e=>{const p=t.swipe;t.swipe=null;if(!p||t.pending||get().paused)return;const dx=e.clientX-p.x,dy=e.clientY-p.y;if(Math.max(Math.abs(dx),Math.abs(dy))<16)return;const to=p.index+(Math.abs(dx)>Math.abs(dy)?dx>0?1:-1:dy>0?8:-8);if(t.g.adjacent(p.index,to)){t.selected=-1;select(p.index);select(to);t.consumeClick=true}}});goals(v)}
 function select(i){const t=s(),g=t.g;if(get().paused||t.finished||t.pending)return;t.hints=null;if(t.selected<0){t.selected=i;Sound.click();render(g.snapshot());return}if(t.selected===i){t.selected=-1;render(g.snapshot());return}if(!g.adjacent(t.selected,i)){t.selected=i;render(g.snapshot());return}const a=t.selected,b=i,before=g.snapshot(),ev=g.swap(a,b);t.selected=-1;const swapped=ev?ev.swapped:{...before,board:before.board.slice(),specials:before.specials.slice(),tokens:before.tokens.slice()};if(!ev)for(const ar of [swapped.board,swapped.specials,swapped.tokens])[ar[a],ar[b]]=[ar[b],ar[a]];t.pending={ev,before,swapped,phase:'swap',index:0,next:get().elapsed+(reduced?40:200)};render(swapped,'swap',before);Sound.matchSwap();message('小猪正在换位置……')}
 function tick(){const t=s(),p=t.pending;if(!p||get().paused||get().elapsed<p.next)return;const duration=n=>reduced?40:n;if(p.phase==='swap'){if(!p.ev){p.phase='return';p.next=get().elapsed+duration(200);render(p.before,'return',p.swapped);Sound.miss();message('这次没有形成三连，小猪换回原位，不扣步数。','warn')}else{p.phase='clear';showClear(p)}}else if(p.phase==='return'){t.pending=null;render(t.g.snapshot())}else if(p.phase==='clear'){p.phase='fall';p.next=get().elapsed+duration(300);const f=p.ev.frames[p.index];render(f.after,'fall',f,f);Sound.matchFall()}else if(p.phase==='fall'){p.index++;if(p.index<p.ev.frames.length){p.phase='clear';showClear(p)}else{t.pending=null;render(p.ev.final);message((p.ev.label?p.ev.label+'！':'')+'这次 +'+p.ev.gained+' 分，连锁 '+p.ev.chain+' 次。'+(p.ev.reshuffled?'棋盘已重排，特殊猪和目标保留。':''));if(t.g.over)helpers.end(t.g.won?'猪猪特技派对成功！':'再试试特技组合。','本局 '+t.g.score+' 分，'+(t.g.won?'所有目标都完成啦！':'还差的目标显示在棋盘上方，火箭和组合技能帮你破冰。'),t.g.won,t.g.score)}}
  function showClear(p){const f=p.ev.frames[p.index];p.next=get().elapsed+duration(330);render(f,'clear',null,f);Sound.matchCascade(f.ids.length,f.chain);for(const kind of [...new Set([...f.created.map(v=>v.kind),...f.effects.map(v=>v.kind)])])Sound.matchPower(kind);message((p.ev.label&&p.index===0?p.ev.label+' · ':'')+'连锁 ×'+f.chain+'，这一波 +'+f.points+' 分。')}
 }
 function hint(){const t=s();if(t.pending)return;t.hints=t.g.findMove();render(t.g.snapshot());Sound.hintSpark();message('圈出的两只可以交换；特殊猪和任意邻居交换都能发动。')}
 return {init,tick,hint,render,select,changeLook:()=>{}};
}
root.PigMatchUI={create,kinds,names,src};
})(typeof window!=='undefined'?window:globalThis);
