const assert=require('node:assert/strict');const C=require('./app/core.js');
for(const [w,h,n] of [[9,9,10],[16,16,40],[30,16,99],[30,20,150]])for(let k=0;k<25;k++){const m=new C.Mine(w,h,n),first=Math.floor(Math.random()*w*h);m.reveal(first);assert(!m.cells[first].pig);assert.equal(m.cells.filter(c=>c.pig).length,n);m.cells.forEach((c,i)=>assert.equal(c.n,m.near(i).filter(j=>m.cells[j].pig).length));m.cells.forEach((c,i)=>{if(!c.pig)m.reveal(i)});assert.equal(m.status,'won')}
const m=new C.Mine(9,9,10);for(let i=0;i<10;i++)m.flag(i);assert(m.flag(0));assert.equal(m.flags,9);m.reveal(0);m.reveal(m.cells.findIndex(c=>c.pig&&!c.flag));assert.equal(m.status,'lost');
assert.deepEqual(C.slideLine([2,2,2,2]),{line:[4,4,0,0],score:8,merged:[0,1]});assert.deepEqual(C.slideLine([2,2,4,0]),{line:[4,4,0,0],score:4,merged:[0]});assert.deepEqual(C.slideLine([4,0,4,4]),{line:[8,4,0,0],score:8,merged:[0]});
const b=[2,0,2,0,4,4,0,0,0,0,0,0,0,0,0,0];assert.deepEqual(C.move2048(b,'right').board,[0,0,0,4,0,0,0,8,0,0,0,0,0,0,0,0]);assert.equal(C.move2048(b,'right').score,12);assert.deepEqual(C.move2048(b,'right').merged.sort(),[3,7]);assert.equal(C.move2048(b,'right').top,8);assert(!C.canMove([2,4,2,4,4,2,4,2,2,4,2,4,4,2,4,2]));assert(C.canMove([2,2,4,8,4,8,2,4,2,4,8,2,4,2,4,8]));
for(let k=0;k<100;k++){let board=Array.from({length:16},()=>Math.random()<.3?0:2**(1+Math.floor(Math.random()*6)));for(const dir of ['left','right','up','down']){const r=C.move2048(board,dir);assert.equal(r.board.reduce((a,b)=>a+b,0),board.reduce((a,b)=>a+b,0));assert(r.board.every(v=>v===0||Number.isInteger(Math.log2(v))))}}
{const w=new C.Mine(9,9,10);w.reveal(40);w.cells.forEach((c,i)=>{if(!c.pig)w.reveal(i)});assert.equal(w.status,'won');assert(w.cells.every(c=>!c.pig||c.flag));assert.equal(w.flags,10)}
for(let k=0;k<30;k++){const L=new C.Mine(30,16,99);L.reveal(0);L.flag(L.cells.findIndex(c=>c.pig));const p=L.cells.findIndex(c=>c.pig&&!c.flag);L.reveal(p);assert.equal(L.status,'lost');const order=L.wakeOrder();assert.equal(order.length,97);assert(!order.includes(L.hit));assert.equal(new Set(order).size,97);assert(order.every(i=>L.cells[i].pig&&!L.cells[i].flag))}
console.log('PASS: win auto-flags every pig; loss wake order covers each unflagged pig once.');
console.log('PASS: 100 mine boards, flag limit reversal, loss, 2048 merge-once rules, all directions, 400 mass-conservation checks.');
